//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/protocol.proto
// Note: requires additional types generated from: proto/packet.proto
namespace com.crownrace.msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"heartbeat_req")]
  public partial class heartbeat_req : global::ProtoBuf.IExtensible
  {
    public heartbeat_req() {}
    
    private ulong _server_timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong server_timestamp
    {
      get { return _server_timestamp; }
      set { _server_timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"heartbeat_ack")]
  public partial class heartbeat_ack : global::ProtoBuf.IExtensible
  {
    public heartbeat_ack() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"login_req")]
  public partial class login_req : global::ProtoBuf.IExtensible
  {
    public login_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"login_ack")]
  public partial class login_ack : global::ProtoBuf.IExtensible
  {
    public login_ack() {}
    
    private com.crownrace.msg.player_data _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.crownrace.msg.player_data data
    {
      get { return _data; }
      set { _data = value; }
    }
    private bool _is_success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_success
    {
      get { return _is_success; }
      set { _is_success = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"leave_game_ntf")]
  public partial class leave_game_ntf : global::ProtoBuf.IExtensible
  {
    public leave_game_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_data")]
  public partial class player_data : global::ProtoBuf.IExtensible
  {
    public player_data() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private string _res_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"res_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string res_name
    {
      get { return _res_name; }
      set { _res_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"all_player_data_ntf")]
  public partial class all_player_data_ntf : global::ProtoBuf.IExtensible
  {
    public all_player_data_ntf() {}
    
    private readonly global::System.Collections.Generic.List<com.crownrace.msg.player_data> _all_player = new global::System.Collections.Generic.List<com.crownrace.msg.player_data>();
    [global::ProtoBuf.ProtoMember(1, Name=@"all_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.crownrace.msg.player_data> all_player
    {
      get { return _all_player; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"message_ntf")]
  public partial class message_ntf : global::ProtoBuf.IExtensible
  {
    public message_ntf() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"set_dice_btn_state_ntf")]
  public partial class set_dice_btn_state_ntf : global::ProtoBuf.IExtensible
  {
    public set_dice_btn_state_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private bool _can_press;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"can_press", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool can_press
    {
      get { return _can_press; }
      set { _can_press = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"set_use_card_state_ntf")]
  public partial class set_use_card_state_ntf : global::ProtoBuf.IExtensible
  {
    public set_use_card_state_ntf() {}
    
    private bool _can_use_card;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"can_use_card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool can_use_card
    {
      get { return _can_use_card; }
      set { _can_use_card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"set_end_round_btn_state_ntf")]
  public partial class set_end_round_btn_state_ntf : global::ProtoBuf.IExtensible
  {
    public set_end_round_btn_state_ntf() {}
    
    private bool _can_end_round;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"can_end_round", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool can_end_round
    {
      get { return _can_end_round; }
      set { _can_end_round = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"use_card_req")]
  public partial class use_card_req : global::ProtoBuf.IExtensible
  {
    public use_card_req() {}
    
    private int _use_player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"use_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int use_player_id
    {
      get { return _use_player_id; }
      set { _use_player_id = value; }
    }
    private int _card_instance_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card_instance_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_instance_id
    {
      get { return _card_instance_id; }
      set { _card_instance_id = value; }
    }
    private int _target_player_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"target_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target_player_id
    {
      get { return _target_player_id; }
      set { _target_player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"use_card_ack")]
  public partial class use_card_ack : global::ProtoBuf.IExtensible
  {
    public use_card_ack() {}
    
    private int _use_player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"use_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int use_player_id
    {
      get { return _use_player_id; }
      set { _use_player_id = value; }
    }
    private bool _is_use_success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_use_success", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_use_success
    {
      get { return _is_use_success; }
      set { _is_use_success = value; }
    }
    private int _card_instance_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card_instance_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_instance_id
    {
      get { return _card_instance_id; }
      set { _card_instance_id = value; }
    }
    private int _have_card_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"have_card_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int have_card_num
    {
      get { return _have_card_num; }
      set { _have_card_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"use_card_ntf")]
  public partial class use_card_ntf : global::ProtoBuf.IExtensible
  {
    public use_card_ntf() {}
    
    private int _use_player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"use_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int use_player_id
    {
      get { return _use_player_id; }
      set { _use_player_id = value; }
    }
    private int _card_instance_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card_instance_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_instance_id
    {
      get { return _card_instance_id; }
      set { _card_instance_id = value; }
    }
    private int _card_config_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card_config_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_config_id
    {
      get { return _card_config_id; }
      set { _card_config_id = value; }
    }
    private int _have_card_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"have_card_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int have_card_num
    {
      get { return _have_card_num; }
      set { _have_card_num = value; }
    }
    private int _target_player_id1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"target_player_id1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target_player_id1
    {
      get { return _target_player_id1; }
      set { _target_player_id1 = value; }
    }
    private int _target_player_id2;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"target_player_id2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target_player_id2
    {
      get { return _target_player_id2; }
      set { _target_player_id2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"remove_player_card_ntf")]
  public partial class remove_player_card_ntf : global::ProtoBuf.IExtensible
  {
    public remove_player_card_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _card_instance_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"card_instance_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> card_instance_id
    {
      get { return _card_instance_id; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _card_config_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"card_config_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> card_config_id
    {
      get { return _card_config_id; }
    }
  
    private int _have_card_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"have_card_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int have_card_num
    {
      get { return _have_card_num; }
      set { _have_card_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"add_player_card_ntf")]
  public partial class add_player_card_ntf : global::ProtoBuf.IExtensible
  {
    public add_player_card_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _card_instance_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"card_instance_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> card_instance_id
    {
      get { return _card_instance_id; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _card_config_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"card_config_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> card_config_id
    {
      get { return _card_config_id; }
    }
  
    private int _have_card_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"have_card_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int have_card_num
    {
      get { return _have_card_num; }
      set { _have_card_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"move_player_ntf")]
  public partial class move_player_ntf : global::ProtoBuf.IExtensible
  {
    public move_player_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private float _pos_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private float _pos_z;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private float _rotation_x;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rotation_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_x
    {
      get { return _rotation_x; }
      set { _rotation_x = value; }
    }
    private float _rotation_y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rotation_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_y
    {
      get { return _rotation_y; }
      set { _rotation_y = value; }
    }
    private float _rotation_z;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"rotation_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_z
    {
      get { return _rotation_z; }
      set { _rotation_z = value; }
    }
    private float _rotation_w;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"rotation_w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_w
    {
      get { return _rotation_w; }
      set { _rotation_w = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"sync_dice_ntf")]
  public partial class sync_dice_ntf : global::ProtoBuf.IExtensible
  {
    public sync_dice_ntf() {}
    
    private bool _is_active;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_active", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_active
    {
      get { return _is_active; }
      set { _is_active = value; }
    }
    private float _pos_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private float _pos_z;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private float _rotation_x;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rotation_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_x
    {
      get { return _rotation_x; }
      set { _rotation_x = value; }
    }
    private float _rotation_y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rotation_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_y
    {
      get { return _rotation_y; }
      set { _rotation_y = value; }
    }
    private float _rotation_z;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"rotation_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_z
    {
      get { return _rotation_z; }
      set { _rotation_z = value; }
    }
    private float _rotation_w;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"rotation_w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_w
    {
      get { return _rotation_w; }
      set { _rotation_w = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"set_player_state_ntf")]
  public partial class set_player_state_ntf : global::ProtoBuf.IExtensible
  {
    public set_player_state_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private com.crownrace.msg.PLAYER_STATE _player_state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.crownrace.msg.PLAYER_STATE player_state
    {
      get { return _player_state; }
      set { _player_state = value; }
    }
    private int _state_round_left;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"state_round_left", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state_round_left
    {
      get { return _state_round_left; }
      set { _state_round_left = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"roll_dice_req")]
  public partial class roll_dice_req : global::ProtoBuf.IExtensible
  {
    public roll_dice_req() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"end_round_req")]
  public partial class end_round_req : global::ProtoBuf.IExtensible
  {
    public end_round_req() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"game_load_over_req")]
  public partial class game_load_over_req : global::ProtoBuf.IExtensible
  {
    public game_load_over_req() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"update_buff_data_ntf")]
  public partial class update_buff_data_ntf : global::ProtoBuf.IExtensible
  {
    public update_buff_data_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<com.crownrace.msg.buff_data> _data = new global::System.Collections.Generic.List<com.crownrace.msg.buff_data>();
    [global::ProtoBuf.ProtoMember(2, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.crownrace.msg.buff_data> data
    {
      get { return _data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"vectory_ntf")]
  public partial class vectory_ntf : global::ProtoBuf.IExtensible
  {
    public vectory_ntf() {}
    
    private string _no1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"no1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string no1
    {
      get { return _no1; }
      set { _no1 = value; }
    }
    private string _no2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"no2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string no2
    {
      get { return _no2; }
      set { _no2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_round_end_req")]
  public partial class player_round_end_req : global::ProtoBuf.IExtensible
  {
    public player_round_end_req() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_move_over_ntf")]
  public partial class player_move_over_ntf : global::ProtoBuf.IExtensible
  {
    public player_move_over_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private int _move_player_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"move_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int move_player_id
    {
      get { return _move_player_id; }
      set { _move_player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cell_effect_req")]
  public partial class cell_effect_req : global::ProtoBuf.IExtensible
  {
    public cell_effect_req() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cell_effect_ack")]
  public partial class cell_effect_ack : global::ProtoBuf.IExtensible
  {
    public cell_effect_ack() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private com.crownrace.msg.CELL_EFFECT _cell_effect;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cell_effect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.crownrace.msg.CELL_EFFECT cell_effect
    {
      get { return _cell_effect; }
      set { _cell_effect = value; }
    }
    private int _effect_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"effect_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int effect_num
    {
      get { return _effect_num; }
      set { _effect_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cell_effect_ntf")]
  public partial class cell_effect_ntf : global::ProtoBuf.IExtensible
  {
    public cell_effect_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private com.crownrace.msg.CELL_EFFECT _cell_effect;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cell_effect", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.crownrace.msg.CELL_EFFECT cell_effect
    {
      get { return _cell_effect; }
      set { _cell_effect = value; }
    }
    private int _effect_num;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"effect_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int effect_num
    {
      get { return _effect_num; }
      set { _effect_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_roll_dice_ntf")]
  public partial class player_roll_dice_ntf : global::ProtoBuf.IExtensible
  {
    public player_roll_dice_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"dice_sync_ntf")]
  public partial class dice_sync_ntf : global::ProtoBuf.IExtensible
  {
    public dice_sync_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private bool _is_active;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"is_active", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_active
    {
      get { return _is_active; }
      set { _is_active = value; }
    }
    private float _pos_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_y;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_y
    {
      get { return _pos_y; }
      set { _pos_y = value; }
    }
    private float _pos_z;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private float _rotation_x;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rotation_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_x
    {
      get { return _rotation_x; }
      set { _rotation_x = value; }
    }
    private float _rotation_y;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rotation_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_y
    {
      get { return _rotation_y; }
      set { _rotation_y = value; }
    }
    private float _rotation_z;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"rotation_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_z
    {
      get { return _rotation_z; }
      set { _rotation_z = value; }
    }
    private float _rotation_w;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"rotation_w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float rotation_w
    {
      get { return _rotation_w; }
      set { _rotation_w = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"roll_dice_over_ntf")]
  public partial class roll_dice_over_ntf : global::ProtoBuf.IExtensible
  {
    public roll_dice_over_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private int _dice_num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dice_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dice_num
    {
      get { return _dice_num; }
      set { _dice_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"move_to_end_ntf")]
  public partial class move_to_end_ntf : global::ProtoBuf.IExtensible
  {
    public move_to_end_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_pause_ntf")]
  public partial class player_pause_ntf : global::ProtoBuf.IExtensible
  {
    public player_pause_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private int _left_pause_round;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"left_pause_round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int left_pause_round
    {
      get { return _left_pause_round; }
      set { _left_pause_round = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"roll_card_req")]
  public partial class roll_card_req : global::ProtoBuf.IExtensible
  {
    public roll_card_req() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"roll_card_ntf")]
  public partial class roll_card_ntf : global::ProtoBuf.IExtensible
  {
    public roll_card_ntf() {}
    
    private int _player_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private int _card_instance_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card_instance_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_instance_id
    {
      get { return _card_instance_id; }
      set { _card_instance_id = value; }
    }
    private int _card_config_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card_config_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card_config_id
    {
      get { return _card_config_id; }
      set { _card_config_id = value; }
    }
    private int _have_card_num;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"have_card_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int have_card_num
    {
      get { return _have_card_num; }
      set { _have_card_num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}